# Generated by Django 3.2.25 on 2025-04-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_organization_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
